// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaU9a0SPwrj3wE5XEAONfEgttKvggaOU',
    appId: '1:534116838579:web:ad457ba77c413c9c6cd4c6',
    messagingSenderId: '534116838579',
    projectId: 'flutter-add-b45a3',
    authDomain: 'flutter-add-b45a3.firebaseapp.com',
    storageBucket: 'flutter-add-b45a3.appspot.com',
    measurementId: 'G-2FF4WZTF8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeUh5quVyXIcqm7D7j6eCR4cOc7F97jQ',
    appId: '1:534116838579:android:2020091f877289f06cd4c6',
    messagingSenderId: '534116838579',
    projectId: 'flutter-add-b45a3',
    storageBucket: 'flutter-add-b45a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4J_NBbmFbUa0o_-u8ExTDDR23Whpx0jY',
    appId: '1:534116838579:ios:44b55870370766156cd4c6',
    messagingSenderId: '534116838579',
    projectId: 'flutter-add-b45a3',
    storageBucket: 'flutter-add-b45a3.appspot.com',
    iosBundleId: 'com.example.moneylover',
  );
}
